# Generated by Django 3.0.2 on 2020-02-05 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='account_pics'),
        ),
    ]
