# Generated by Django 3.0.2 on 2020-02-10 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_item_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='size',
            field=models.CharField(choices=[('NA', 'N/A'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], default='S', max_length=2),
        ),
    ]
