# Generated by Django 3.0.2 on 2020-06-07 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_payment_order_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='order_number',
        ),
    ]
